[package]
name = "fluoris"
version = "0.1.0"
edition = "2024"

[dependencies]
sqlx = { version = "0.8.6", features = [
    "postgres",
    "runtime-tokio-native-tls",
    "macros",
    "migrate",
] }
dotenv = "0.15.0"
poise = "0.6.1"
reqwest = { version = "0.13.2", features = ["json"] }
serde = "1.0.228"
tokio = { version = "1.49.0", features = ["full"] }
mockito = "1.7.2"
serde_json = "1.0.149"
rcon = { version = "0.6.0", features = ["rt-tokio"] }
