
CREATE TABLE IF NOT EXISTS MC (
    UUID BIGINT PRIMARY KEY GENERATED ALWAYS AS IDENTITY,
    MCID    TEXT UNIQUE,
    MCUser  TEXT UNIQUE,
    Discord TEXT UNIQUE
);

CREATE UNIQUE INDEX MC_INDEX ON MC (MCID, MCUser, Discord);
